### ISSUE TITLE
wrong slide title

### ISSUE THREAD

**Issue by maelle** [brunaw/julia-tutorial#1]
Thanks for sharing your slides!

I noticed that the tab in my browser had the wrong title, because of 

https://github.com/brunaw/julia-tutorial/blob/0927fbebbe5eb8b407ed14c9c6440b6ade4497ea/slides/julia.html#L4

**Comment by brunaw** [comment]
Thanks @maelle! I had changed it in the .rmd but didn't compile again, sorry about that!
